// ---------------------------------------------------------------------------
// test_reader.cpp — Unit tests for audio/reader.h
//
// Coverage:
//   read_wav()
//     ValidSilenceCorrectSampleCount   — 16 kHz mono → 4000 samples
//     Sine44kHzCorrectSampleRate       — sample_rate == 44100
//     StereoChannelCountIsTwo          — channels == 2, 22050 total samples
//     NonExistentFileThrows            — missing path → runtime_error
//     TruncatedWavThrows               — header OK, sample data missing → throws
//     ListChunkBeforeDataSkipped       — LIST chunk between fmt and data → OK
//     UnsupportedFormatThrows          — μ-law (code 7) → exact error message
//
//   peek_wav_duration_secs()
//     ReturnsCorrectDuration           — 0.25 s fixture
//
//   read_pcm()
//     ReadsRawPcmWithAssumedMetadata   — size/rate/channels
//
// Fixtures in engine/tests/fixtures/ are pre-generated by generate_wav.py
// and committed to the repo.  Synthetic WAVs for edge cases are written to
// /tmp by TempFile and cleaned up automatically by its destructor.
// ---------------------------------------------------------------------------

#include <gtest/gtest.h>

#include <cstdint>
#include <cstring>
#include <fstream>
#include <stdexcept>
#include <string>
#include <unistd.h>  // mkstemp, write, close, unlink
#include <vector>

#include "audio/reader.h"

// ===========================================================================
// Path helpers
// ===========================================================================

// Derive the fixtures directory from the source file's own absolute path.
// CMake on macOS passes absolute source paths to the compiler, so __FILE__
// is guaranteed to be absolute in our build environment.
static std::string fixtures_dir() {
    std::string p = __FILE__;            // …/engine/tests/test_reader.cpp
    auto sep = p.find_last_of("/\\");
    return (sep != std::string::npos ? p.substr(0, sep + 1) : std::string("./"))
           + "fixtures/";
}

// ===========================================================================
// TempFile — RAII temp-file written from a raw byte buffer
// ===========================================================================

class TempFile {
public:
    explicit TempFile(const std::vector<uint8_t>& data) {
        char tmpl[] = "/tmp/openverb_test_reader_XXXXXX";
        int fd = mkstemp(tmpl);
        if (fd < 0)
            throw std::runtime_error("mkstemp failed");
        path_ = tmpl;
        ::write(fd, data.data(), static_cast<ssize_t>(data.size()));
        ::close(fd);
    }
    ~TempFile() { if (!path_.empty()) ::unlink(path_.c_str()); }

    const std::string& path() const { return path_; }

private:
    std::string path_;
};

// ===========================================================================
// Synthetic WAV builder
// ===========================================================================

// Build a minimal RIFF/WAVE PCM file in memory.
//
// Parameters:
//   fmt_code        — audio format code (1 = PCM; 7 = μ-law; 2 = ADPCM; …)
//   channels        — number of channels
//   sample_rate     — samples per second per channel
//   bits_per_sample — bit depth (16 for our fixtures)
//   samples         — interleaved PCM samples (int16 LE)
//   insert_list     — if true, insert a minimal LIST chunk between fmt and data
//   extra_fmt_bytes — extra zero bytes appended to the fmt payload (used to
//                     create odd-sized fmt chunks to exercise RIFF pad handling)
//
// The returned buffer is a byte-accurate RIFF/WAVE file.
static std::vector<uint8_t> make_wav_bytes(
    uint16_t fmt_code,
    uint16_t channels,
    uint32_t sample_rate,
    uint16_t bits_per_sample,
    const std::vector<int16_t>& samples,
    bool insert_list = false,
    uint32_t extra_fmt_bytes = 0)
{
    std::vector<uint8_t> out;

    auto w16 = [&](uint16_t v) {
        out.push_back(static_cast<uint8_t>(v & 0xFF));
        out.push_back(static_cast<uint8_t>((v >> 8) & 0xFF));
    };
    auto w32 = [&](uint32_t v) {
        out.push_back(static_cast<uint8_t>(v & 0xFF));
        out.push_back(static_cast<uint8_t>((v >> 8)  & 0xFF));
        out.push_back(static_cast<uint8_t>((v >> 16) & 0xFF));
        out.push_back(static_cast<uint8_t>((v >> 24) & 0xFF));
    };
    auto w4 = [&](const char* cc) {
        out.push_back(static_cast<uint8_t>(cc[0]));
        out.push_back(static_cast<uint8_t>(cc[1]));
        out.push_back(static_cast<uint8_t>(cc[2]));
        out.push_back(static_cast<uint8_t>(cc[3]));
    };

    uint32_t bps_bytes   = bits_per_sample / 8u;
    uint32_t data_size   = static_cast<uint32_t>(samples.size()) * bps_bytes;
    uint32_t byte_rate   = sample_rate * channels * bps_bytes;
    uint16_t block_align = static_cast<uint16_t>(channels * bps_bytes);

    // fmt chunk payload = 16 standard bytes + any extra bytes for testing
    uint32_t fmt_payload = 16u + extra_fmt_bytes;
    // RIFF spec: chunk payloads are padded to an even byte boundary
    uint32_t fmt_pad     = fmt_payload & 1u;  // 1 if odd, 0 if even

    // A minimal LIST chunk: "LIST" header (8) + "INFO" type (4) = 12 bytes total.
    // chunk_size = 4 (just the list-type field, no sub-chunks).
    constexpr uint32_t LIST_CHUNK_SIZE  = 4u;   // content size
    constexpr uint32_t LIST_CHUNK_TOTAL = 8u + LIST_CHUNK_SIZE;

    // RIFF content = "WAVE" (4) + fmt chunk (8+payload+pad) + optional LIST (12) + data chunk
    uint32_t riff_content =
          4u                                               // "WAVE"
        + 8u + fmt_payload + fmt_pad                      // fmt chunk (hdr + payload + pad)
        + (insert_list ? LIST_CHUNK_TOTAL : 0u)           // LIST chunk
        + 8u + data_size;                                 // data chunk

    // ── RIFF descriptor ──────────────────────────────────────────────────────
    w4("RIFF");
    w32(riff_content);
    w4("WAVE");

    // ── fmt chunk ────────────────────────────────────────────────────────────
    w4("fmt ");
    w32(fmt_payload);     // chunk payload size
    w16(fmt_code);
    w16(channels);
    w32(sample_rate);
    w32(byte_rate);
    w16(block_align);
    w16(bits_per_sample);
    // extra bytes (zeros) — used to produce odd-sized fmt chunks in tests
    for (uint32_t i = 0; i < extra_fmt_bytes; ++i)
        out.push_back(0);
    // RIFF alignment pad byte (written only when payload is odd-sized)
    if (fmt_pad)
        out.push_back(0);

    // ── optional LIST chunk (between fmt and data) ────────────────────────────
    if (insert_list) {
        w4("LIST");
        w32(LIST_CHUNK_SIZE);  // payload = just the list-type word
        w4("INFO");            // list type
    }

    // ── data chunk ───────────────────────────────────────────────────────────
    w4("data");
    w32(data_size);
    for (int16_t s : samples) {
        out.push_back(static_cast<uint8_t>(s & 0xFF));
        out.push_back(static_cast<uint8_t>((s >> 8) & 0xFF));
    }

    return out;
}

// ===========================================================================
// Tests: read_wav — committed fixtures
// ===========================================================================

TEST(ReadWav, ValidSilenceCorrectSampleCount) {
    // silence.wav: mono, 16000 Hz, 16-bit, 0.25 s → 4000 samples
    AudioData audio = read_wav(fixtures_dir() + "silence.wav");
    EXPECT_EQ(audio.samples.size(), 4000u);
    EXPECT_EQ(audio.sample_rate, 16000);
    EXPECT_EQ(audio.channels, 1);
    EXPECT_EQ(audio.bits_per_sample, 16);
}

TEST(ReadWav, Sine44kHzCorrectSampleRate) {
    // sine_440hz.wav: mono, 44100 Hz, 16-bit, 0.25 s → 11025 samples
    AudioData audio = read_wav(fixtures_dir() + "sine_440hz.wav");
    EXPECT_EQ(audio.sample_rate, 44100);
    EXPECT_EQ(audio.samples.size(), 11025u);
    EXPECT_EQ(audio.channels, 1);
}

TEST(ReadWav, StereoChannelCountIsTwo) {
    // stereo.wav: stereo, 44100 Hz, 16-bit, 0.25 s
    //   → 11025 frames × 2 channels = 22050 interleaved samples
    AudioData audio = read_wav(fixtures_dir() + "stereo.wav");
    EXPECT_EQ(audio.channels, 2);
    EXPECT_EQ(audio.sample_rate, 44100);
    EXPECT_EQ(audio.samples.size(), 22050u);
}

// ===========================================================================
// Tests: read_wav — synthetic edge cases
// ===========================================================================

TEST(ReadWav, NonExistentFileThrows) {
    EXPECT_THROW(
        read_wav("/no/such/path/openverb_ghost_file.wav"),
        std::runtime_error);
}

TEST(ReadWav, TruncatedWavThrows) {
    // Build a valid 100-sample WAV, then truncate the buffer to just 44 bytes
    // (the complete RIFF/fmt/data headers but zero sample bytes).
    // The data chunk header declares 200 bytes of payload that aren't there,
    // so must_read() will fail with "unexpected end of file".
    std::vector<int16_t> samples(100, 0);
    auto data = make_wav_bytes(1, 1, 16000, 16, samples);

    // 44 bytes = 8(RIFF hdr) + 4(WAVE) + 8+16(fmt chunk) + 8(data hdr)
    data.resize(44);

    TempFile tmp(data);
    EXPECT_THROW(read_wav(tmp.path()), std::runtime_error);
}

TEST(ReadWav, ListChunkBeforeDataSkippedGracefully) {
    // A WAV with: RIFF → fmt → LIST → data
    // The reader must skip the LIST chunk and still decode correctly.
    std::vector<int16_t> samples = {10, 20, 30, 40, 50, 60, 70, 80};
    auto data = make_wav_bytes(1, 1, 16000, 16, samples, /*insert_list=*/true);

    TempFile tmp(data);
    AudioData audio = read_wav(tmp.path());

    EXPECT_EQ(audio.samples.size(), 8u);
    EXPECT_EQ(audio.sample_rate, 16000);
    EXPECT_EQ(audio.channels, 1);
    // Verify sample values survive the round-trip
    EXPECT_EQ(audio.samples[0], 10);
    EXPECT_EQ(audio.samples[7], 80);
}

TEST(ReadWav, UnsupportedFormatThrowsWithMessage) {
    // Format code 7 = μ-law (G.711); not PCM.  The reader must throw with the
    // exact message "unsupported WAV format: only PCM (format 1) supported".
    auto data = make_wav_bytes(/*fmt_code=*/7, 1, 8000, 16, {});

    TempFile tmp(data);

    // 1. It must throw std::runtime_error.
    EXPECT_THROW(read_wav(tmp.path()), std::runtime_error);

    // 2. The error message must be exact.
    try {
        read_wav(tmp.path());
        FAIL() << "Expected std::runtime_error to be thrown";
    } catch (const std::runtime_error& e) {
        EXPECT_STREQ(e.what(),
                     "unsupported WAV format: only PCM (format 1) supported");
    }
}

TEST(ReadWav, Non16BitPcmThrows) {
    // An 8-bit PCM WAV (format code 1, bits_per_sample 8) is valid RIFF/WAVE
    // but read_wav() must reject it because decoding into int16_t would require
    // either a 2× over-read (bogus EOF) or an 8→16 conversion we don't do.
    // Empty samples: data_size=0 keeps the WAV header self-consistent for 8-bit.
    auto data = make_wav_bytes(/*fmt_code=*/1, 1, 16000, /*bps=*/8, {});

    TempFile tmp(data);
    EXPECT_THROW(read_wav(tmp.path()), std::runtime_error);

    try {
        read_wav(tmp.path());
        FAIL() << "Expected std::runtime_error to be thrown";
    } catch (const std::runtime_error& e) {
        EXPECT_STREQ(e.what(),
                     "unsupported WAV bit depth: only 16-bit PCM is supported");
    }
}

TEST(ReadWav, OddSizedFmtChunkHandled) {
    // A fmt chunk with payload size 17 (odd) must be followed by a silent RIFF
    // pad byte.  The reader must consume the pad so the next chunk header is
    // aligned; if it doesn't, it will mis-read the 'data' fourCC and fail.
    //
    // We pass extra_fmt_bytes=1 → fmt chunk_size = 17 (odd) → 1 pad byte in file.
    // After the fix the reader skips (17-16) + (17&1) = 1+1 = 2 bytes and then
    // finds the data chunk correctly.
    std::vector<int16_t> samples = {1, 2, 3, 4};
    auto data = make_wav_bytes(/*fmt_code=*/1, 1, 16000, 16, samples,
                               /*insert_list=*/false, /*extra_fmt_bytes=*/1);

    TempFile tmp(data);
    AudioData audio = read_wav(tmp.path());

    EXPECT_EQ(audio.samples.size(), 4u);
    EXPECT_EQ(audio.sample_rate,    16000);
    EXPECT_EQ(audio.channels,       1);
    EXPECT_EQ(audio.samples[0],     1);
    EXPECT_EQ(audio.samples[3],     4);
}

// ===========================================================================
// Tests: peek_wav_duration_secs
// ===========================================================================

TEST(PeekWavDuration, ReturnsCorrectDuration) {
    // All three committed fixtures are 0.25 s; verify with a tight tolerance.
    const double tol = 1e-6;
    EXPECT_NEAR(peek_wav_duration_secs(fixtures_dir() + "silence.wav"),    0.25, tol);
    EXPECT_NEAR(peek_wav_duration_secs(fixtures_dir() + "sine_440hz.wav"), 0.25, tol);
    EXPECT_NEAR(peek_wav_duration_secs(fixtures_dir() + "stereo.wav"),     0.25, tol);
}

TEST(PeekWavDuration, NonExistentFileThrows) {
    EXPECT_THROW(
        peek_wav_duration_secs("/no/such/openverb_ghost.wav"),
        std::runtime_error);
}

// ===========================================================================
// Tests: read_pcm
// ===========================================================================

TEST(ReadPcm, ReadsRawPcmWithAssumedMetadata) {
    // Write 200 raw int16_t samples (no WAV header) to a temp file and verify
    // that read_pcm() fills in the hardcoded 16 kHz / mono / 16-bit contract.
    constexpr std::size_t N = 200;
    std::vector<uint8_t> raw(N * sizeof(int16_t), 0);
    // Write sample index as value so we can verify round-trip.
    for (std::size_t i = 0; i < N; ++i) {
        int16_t v = static_cast<int16_t>(i);
        raw[i * 2]     = static_cast<uint8_t>(v & 0xFF);
        raw[i * 2 + 1] = static_cast<uint8_t>((v >> 8) & 0xFF);
    }

    TempFile tmp(raw);
    AudioData audio = read_pcm(tmp.path());

    EXPECT_EQ(audio.samples.size(), N);
    EXPECT_EQ(audio.sample_rate, 16000);
    EXPECT_EQ(audio.channels, 1);
    EXPECT_EQ(audio.bits_per_sample, 16);
    EXPECT_EQ(audio.samples[0],   0);
    EXPECT_EQ(audio.samples[199], 199);
}

TEST(ReadPcm, NonExistentFileThrows) {
    EXPECT_THROW(
        read_pcm("/no/such/openverb_ghost.pcm"),
        std::runtime_error);
}
